### ISSUE TITLE
运行run_epoch.py时报错

### ISSUE THREAD

**Issue by Balabala125** [gaussic/text-classification-cnn-rnn#1]
您好，我打算复现一下您的程序，但是当运行run_epoch.py文件时，程序报错：
ImportError: No module named data.cnews_loader
我看了您的程序里面确实没有这个模块，我应该怎么办呢？谢谢啦
还有，顺带问一下，cnews_loader.py后面的main函数为什么要注释掉呢？
（自然语言处理刚入门，还望您解答一下，再次感谢！！！）

**Comment by gaussic** [comment]
fixed

**Comment by Balabala125** [comment]
好的，我试试，谢谢啦！如果有问题，还会来请教您的

**Comment by gaussic** [comment]
等我现在在pycharm里面做一下修改，你重新克隆一下

**Comment by gaussic** [comment]
@Balabala125 你好，问题已经修复了，现在可以pull新的版本了。

**Comment by Balabala125** [comment]
真是太棒了！
还有就是我是python2.7，那个程序依赖于python3，并且我的tensorflow也是基于python2的，我应该如何修改一下呢？（这个问题貌似有点太苛刻了）

**Comment by Balabala125** [comment]
好的，我重新试一下，再次感谢

**Comment by gaussic** [comment]
python2.7的话应该没有太多要修改的地方，你运行一遍看看有没有什么报错信息

**Comment by Balabala125** [comment]
就是编码问题
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by gaussic** [comment]
这个问题，你试试把cnews_loader.py中所有的open()函数的`encoding='utf-8'`删除掉，然后再运行。

**Comment by Balabala125** [comment]
我运行run_epoch.py这个文件时，报错，没有vocab_cnews.txt这个文件
IOError: [Errno 2] No such file or directory: 'data/cnews/vocab_cnews.txt'

**Comment by gaussic** [comment]
在cnews-loader的main 里面有一个build-vocab的调用，会生成词汇表文件

**Comment by Balabala125** [comment]
解决啦，这个问题，但是我运行那个rnn模型的时候，它又报错了
ValueError: Cannot feed value of shape (128, 9) for Tensor u'input_y:0', which has shape '(?, 10)'

**Comment by gaussic** [comment]
这个问题就涉及具体了，你的数据集只有9个类别吗

**Comment by Balabala125** [comment]
对，我只选了9类，数据太大洛

**Comment by gaussic** [comment]
在loader里面，把类别改为9个，在configuration 里面类别数改为9

**Comment by Balabala125** [comment]
可以啦，真是太感谢了，顺便问一句，您跑rnn，跑洛多久才结束呀？我是在cpu下进行的

**Comment by gaussic** [comment]
😄 那你得做好心理准备了，我用GPU在完整数据集上跑100轮花了将近7个小时，不过跑10轮就已经达到90%，CNN的模型要快很多。

**Comment by Balabala125** [comment]
我运行了差不多快1个小时了，还只迭代了一次，我都怀疑是不是哪里出错洛，感觉都不会动的

**Comment by Balabala125** [comment]
我突然发现不是不会动，是它没有每一次迭代都显示，好像每200次才显示，现在准确率已经达到80%了，非常感谢！！！

**Comment by gaussic** [comment]
嗯，多看代码才能进步
