### ISSUE TITLE
如何写一个方法，接收一个文本为输入，然后返回该文本的分类呢？

### ISSUE THREAD

**Issue by wuxiongliu1** [gaussic/text-classification-cnn-rnn#10]
楼主您好，如何写一个方法，接收一个文本为输入，然后返回该文本的分类呢？

**Comment by gaussic** [comment]
参照test()来写，把batch_size设置为1

**Comment by wuxiongliu1** [comment]
test 中的y_pred_cls 即y的预测分类值是分类值的索引对吗？

另求一问：如果一批数据，训练数据分类为A，然后同时这批数据作为分类B来训练，那后续测试的时候，对于这批数据，能否同时得到两个分类A和B呢?

**Comment by gaussic** [comment]
多标签分类的话，有多标签分类的方法和机制，这一点我不太熟

**Comment by wuxiongliu1** [comment]
好的，谢谢了。
