### ISSUE TITLE
能否在源码中增加一个类似predict的这样的方法？

### ISSUE THREAD

**Issue by wuxiongliu1** [gaussic/text-classification-cnn-rnn#11]
楼主，能否在源码中增加一个predict这样的预测一句话的分类的方法呢？（实在是自己小白一枚，而test方法又看不太懂，输出结果也不是很理解）所以如果楼主有时间的话，能否在源码中增加这样一个方法，接收一句话，输出该句话的分类。（打扰，万分感谢。）

**Comment by commissarster** [comment]
看这里，mittlin/text-classification-cnn-rnn@8093d6f103c0fb69aa3de586775475a28d39baa5
