### ISSUE TITLE
cnews_loader.py 中的问题

### ISSUE THREAD

**Issue by SevenMpp** [gaussic/text-classification-cnn-rnn#112]
Traceback (most recent call last):
  File "run_cnn.py", line 16, in <module>
    from data_process import read_vocab, read_category, batch_iter, process_file, build_vocab
  File "F:\Tools\test\cnn_class\data_process.py", line 145, in <module>
    process_file(train_dir,word,cut,max_length=600)
  File "F:\Tools\test\cnn_class\data_process.py", line 115, in process_file
    label_id.append(cat_to_id[labels[i]])
KeyError: '体育“
我在其他的代码中 就可以 不知道为什么在这个代码里就是总包这个错误

**Comment by reporter-law** [comment]
> 追溯（最近一次调用）：
> 文件“ run_cnn.py”，行16，
> 来自data_process导入read_vocab，read_category，batch_iter，process_file，build_vocab
> 文件“ F：\ Tools \ test \ cnn_class \ data_process.py”，行145，在
> process_file（train_dir，word，cut，max_length = 600）中的
> 文件“ F：\ Tools \ test \ cnn_class \ data_process.py”，行115，在process_file中
> label_id.append（cat_to_id [labels [i]]））
> KeyError：'体育“
> 我在其他的代码中就可以不知道为什么在这个代码里就是总包这个错误

请问解决了吗？
