### ISSUE TITLE
您好，运行run_run.py文件时，只显示了第一行然后就没有任何结果被打印出来，怎么回事？麻烦您了

### ISSUE THREAD

**Issue by SuiYiJie** [gaussic/text-classification-cnn-rnn#113]
您好， 我有一个问题需要请教您。我运行run_cun.py文件是没有问题，无非就是CPU占用高达百分之九十几，但是会有结果出来，大概一个小时的样子。但是当我运行run_run.py文件进行train时，却只打印出一行训练结果，就再也没有下文了，但是听笔记本的声音，应该是还在跑，但是我跑了一夜还是老样子啊。希望您百忙之中抽空解答一下，给您添麻烦了
![run_rnn运行问题](https://user-images.githubusercontent.com/38950582/56088797-3fdeba00-5eba-11e9-984b-5ed558bc2934.png)

**Comment by potatoper** [comment]
请问怎么让 run_cnn.py跑起来  我的一直提示 140行下边的NameError: name 'word_to_id' is not defined。。。愁人

**Comment by SuiYiJie** [comment]
就是按照作者的要去正常跑就行了，已经在我的电脑上跑起来了，没有错误啊……是不是你的数据集没有下载啊？要先下载数据集才行

**Comment by SuiYiJie** [comment]
> 请问怎么让 run_cnn.py跑起来 我的一直提示 140行下边的NameError: name 'word_to_id' is not defined。。。愁人

就是按照作者的要去正常跑就行了，已经在我的电脑上跑起来了，没有错误啊……是不是你的数据集没有下载啊？要先下载数据集才行

**Comment by Quark-own** [comment]
@potatoper 您好，我想问一下，您之前的这个问题解决了吗？我也碰到了这个问题，希望得到您的回复，谢谢。

**Comment by Kangjia0123** [comment]
> @potatoper 您好，我想问一下，您之前的这个问题解决了吗？我也碰到了这个问题，希望得到您的回复，谢谢。

你好，请问你的问题解决了嘛？我也是碰到和您一样的问题
