### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by Mariobai** [gaussic/text-classification-cnn-rnn#12]
我在运行cnews_loader.py和cnews_group.py这两个文件的时间根本的不到我的训练数据啊，在cnews_loader.py这个文件中，根本没有看到数据的输入，而且在cnews_group.py这个文件中只是清空我之前cnew.train.txt文件中原有的数据。您的这个程序到底怎么执行啊？

**Comment by gaussic** [comment]
cnews_group.py是对你从原来的网站下载下来的数据整理，我提供的是已经整理好的版本。

**Comment by Mariobai** [comment]
哦哦。。。好的我知道了。谢谢

**Comment by Mariobai** [comment]
您好，我先问下，为什么
def build_vocab(train_dir, vocab_dir, vocab_size=5000):
    这个地方的vocab_size 的大小设置为5000,这个vocab_size的大小不应该和词汇表的大小是一致的吗？这个5000是根据什么原理取值的啊？

**Comment by gaussic** [comment]
词汇表的生成是文本处理的惯用伎俩。在一个语料库中有时可能有数万个词，但并不是所有的词都是以相同的频率出现的。如果我有100万篇文档分10个类，但是有一个词只出现了五六次，那这个词的意义大吗？

词汇表的生成过程首先统计语料库中所有词的词频并从大到小排序，然后再取前vocab_size个词作为词汇表，这样就去除了很多的噪声，简化了模型。

至于这个vocab_size怎么取，就需要对语料库进行分析。比如总共有100000个词，第30000词出现了50次，第50000个词出现了5次，第60000个词出现了1次，理论上来说vocab_size取50000更为优秀，因为取30000可能忽略了大量的信息，取60000以上有可能多了很多噪声。

这个参数是可以调整的，你应该做的是选择不同的vocab_size，然后去逐个尝试哪个效果要好。

**Comment by Mariobai** [comment]
哦哦。。。好的。非常谢谢您的解答，说的很清楚，谢谢

**Comment by bikachu** [comment]
大神，我是小白。我跟着你的代码敲了一遍，运行时出现File "<ipython-input-8-3cb4ef59a996>", line 177, in <module>
    raise ValueError("""usage: python run_cnn.py [train / test]""")

ValueError: usage: python run_cnn.py [train / test]

运行你的的源代码也是一样的问题。。。，请问怎么解决这个问题？（原谅我的愚昧）

**Comment by LGTH** [comment]
可以翻译这段报错，在run_cnn.py的177行提示的报错，参数错误，命令行用法是python run_cnn.py train或者python run_cnn.py test;你没有加train和test参数导致的

**Comment by LGTH** [comment]
@Bikachu 可以翻译这段报错，在run_cnn.py的177行提示的报错-参数错误，命令行用法是python run_cnn.py train或者python run_cnn.py test;你没有加train和test参数导致的

**Comment by Mariobai** [comment]
@LGTH 楼上正解，你可以在cmd里面去跑这些程序，或者你自己手动的去修改一下程序，让默认就是使用train。

**Comment by bikachu** [comment]
@leoloee @LGTH 你好，我在CMD里面run也是同样的错误提示，请问怎么程序怎么改？

**Comment by gaussic** [comment]
@Bikachu 代码是死的，人是活的。楼上两位已经讲的非常详细了。实在运行不了就改代码，把 `__main__`下面的代码全改掉。
