### ISSUE TITLE
run run_cnn.py is error

### ISSUE THREAD

**Issue by zxyscz** [gaussic/text-classification-cnn-rnn#123]
i run then run_cnn.py,but i have got an error 
def test():
        print("Loading test data...")
        start_time = time.time()
>       x_test, y_test = process_file(test_dir, word_to_id, cat_to_id, config.seq_length)
E       NameError: name 'word_to_id' is not defined

run_cnn.py:145: NameError
 i do not  change the code, how can i solve the problem

**Comment by zxyscz** [comment]
i can run ,please ignore the message

**Comment by Quark-own** [comment]
@zxyscz I have got an error like this. Could you tell me how to solve it?
