### ISSUE TITLE
请问cnews.vocab.txt这个是干什么的？

### ISSUE THREAD

**Issue by wqcqikvc** [gaussic/text-classification-cnn-rnn#129]

**Comment by StarZhai** [comment]
我也有同样的疑问，感觉像是停顿词用的。统计的时候把这些字词去除掉认为他们是不影响分类的词语。

**Comment by gaussic** [comment]
cnew.vocab.txt保存了每一个字以及它们对应的顺序，为了让他们再载入时，和我们训练时的顺序相同，vocab是vocabulary词汇的缩写。
