### ISSUE TITLE
使用CNN进行短文本分类时有哪些参数可以调参?

### ISSUE THREAD

**Issue by commissarster** [gaussic/text-classification-cnn-rnn#13]
在阅读 [Implementing a CNN for Text Classification in TensorFlow](http://www.wildml.com/2015/12/implementing-a-cnn-for-text-classification-in-tensorflow/) 这篇文章时，有几个不太明白的地方，希望能交流一下。

1. 在 dennybritz大牛的文中，使用了3种尺寸的卷积分别是[3、4、5]。而在当前项目好像是只使用了卷积尺寸是5。这两者有什么区别？
2. 如果是对短文本进行分类，调下面几个参数是否可以？

    embedding_dim = 12      # 词向量维度，
    seq_length = 50        # 序列长度，这是代表每个文档的字符长度？
    num_filters = 128        # 卷积核数目
    kernel_size = 5         # 卷积核尺寸
    vocab_size = 5000       # 词汇表达小
    hidden_dim = 128        # 全连接层神经元

3. 在字符级别的CNN在中文的分类与英文的分类方面有什么区别吗？

**Comment by gaussic** [comment]
1. 区别在于，dennybritz是基于论文并在指定数据集上的实现，而这边给出的相当于一个所有模型的baseline，只需要对模型经过稍微的修改，就能重复利用其他代码。

2. config里面的参数基本上都是可调的，seq_length是文本的序列长度，character-level就是多少个字符，word-level就是有多少个词。具体取多少需要分析你的数据集，最大、最小、平均多长，然后再去评估取多大的固定长度为好。

3. 中文的字符个数大约在6000左右，而经过清洗的英文大约字符在100以内。因此，中文的字符需要添加一个Embedding层，而英文的可以考虑直接对每个字符进行one-hot编码。

**Comment by ruoshui-nj** [comment]
您好，一直很关注您的text classification工作。

我想请问下，您提到经过清洗的英文大约字符100多个，是不是指26个英文字母这一粒度的字符呢？

希望得到您的回复，谢谢！

发自我的 iPhone

**Comment by gaussic** [comment]
26个英文字母分大小写就有52个，再加一些在英文中常出现的标点符号，总共可能会达到100个。

例如：

```
-,;.!?:’’’/\|_@#$%ˆ&*˜‘+-=<>()[]{}
```

**Comment by ruoshui-nj** [comment]
明白啦，谢谢！

发自我的 iPhone

**Comment by commissarster** [comment]
@gaussic 非常感谢你的回复，但我有一个不太理解的问题还想请教一下。通过论文我可以形象的理解基于单词的CNN，（一句话转化成了一个二维的图像：每一列是一个词的word2vec向量，每一行是这句话的每个词按序排列）。但基于字符的CNN，这个图像要如何理解？

**Comment by gaussic** [comment]
这个有很大的区别吗？词和字符唯一的区别是粒度不一样。

模型仍然是将已计划转化成一个二维图像，但每一列是一个字的字向量，每一行是这句话的每个字按序排列。

**Comment by commissarster** [comment]
刚才和朋友一起聊了一下这个，好像有点明白了。谢谢 @gaussic 啊
