### ISSUE TITLE
运行 run_cnn.py 出错，直接在pycharm 运行？？

### ISSUE THREAD

**Issue by rick29sz** [gaussic/text-classification-cnn-rnn#134]
问题如下:
【pycharm运行】
/anaconda3/bin/python3.7 /Users/..../PycharmProjects/text-classification-cnn-rnn-master/run_cnn.py
WARNING:tensorflow:From /anaconda3/lib/python3.7/site-packages/tensorflow/python/compat/compat.py:175: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/Users/..../PycharmProjects/text-classification-cnn-rnn-master/run_cnn.py", line 189, in <module>
    raise ValueError("""usage: python run_cnn.py [train / test]""")
ValueError: usage: python run_cnn.py [train / test]

Process finished with exit code 1

【Mac终端运行】：
  File "run_cnn.py", line 13, in <module>
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by lwd45** [comment]
No module named 'tensorflow'

**Comment by Yuhehe** [comment]
没导入好吧
