### ISSUE TITLE
短文本分类

### ISSUE THREAD

**Issue by wlxhappiness** [gaussic/text-classification-cnn-rnn#136]
我目前想要将这分代码用在我的段文本分类上面，请问我需要调整哪些参数呢

**Comment by gaussic** [comment]
调整序列长度，网络结构，词汇表等等

**Comment by wlxhappiness** [comment]
嗯，首先谢谢您的回答，基于您的字符cnn，我放入了自己的中文语料，又加入了词向量，但是准确率还是很低，只有百分之六十几

**Comment by gaussic** [comment]
先尝试传统的分类方法，跑几个简单的模型，神经网络的方法不一定对所有模型有效

**Comment by StarZhai** [comment]
请问这个框架怎么添加公共的词向量（比如百度或者人民日报收集的词向量）或者自己生成的词向量。我下载的项目中没有找到那个文件适合词向量有关系的，并且在run_cnn.py这个文件中也没找到涉及到词向量的代码。

**Comment by StarZhai** [comment]
@wlxhappiness

**Comment by StarZhai** [comment]
@gaussic

**Comment by gaussic** [comment]
词向量的配置在模型中，具体配置还请网上查阅，这里不做赘述。
