### ISSUE TITLE
寻求数据集合

### ISSUE THREAD

**Issue by Yazooliu** [gaussic/text-classification-cnn-rnn#137]
首先对作者的贡献点赞、
作者的数据样本质量很好，即使不是神经网络，使用TF-IDF CounterVector 也可是获得比较好的分类准确率。
但是现在的数据只有5w左右，可否在知道从哪里可以下载到类似高质量更多的数据。我想用更多的数据做实验，谢谢！

**Comment by gaussic** [comment]
https://zhuanlan.zhihu.com/p/25138563
