### ISSUE TITLE
运行python python run_cnn.py test报错

### ISSUE THREAD

**Issue by rainoffallingstar** [gaussic/text-classification-cnn-rnn#139]
用的自己的数据集，前面都正常操作。
python3.6.4+tensorflow1.14.0+cudnn7
报错显示：
ValueError:the passed save_path is not a valid checkpoint:checkpoints/textcnn/best_validation
新手，拜托了。

**Comment by gaussic** [comment]
前面的操作估计有问题，创建目录可能没有成功，再看看save_path试试

**Comment by rainoffallingstar** [comment]
检查了一下，确实是train时候val没有加载，模型未保存，路径无误。已解决

发自我的iPad
