### ISSUE TITLE
是否考虑加入对字向量、词向量的支持?

### ISSUE THREAD

**Issue by agilelab** [gaussic/text-classification-cnn-rnn#140]
有一个疑问，怎么不考虑加入词向量或者字向量的支持呢？

**Comment by gaussic** [comment]
实现这个目的是希望把它做成一套他人可以轻易扩展的文本分类框架，我这里仅作为baseline使用，保持它轻量化的宗旨。

这个框架中已经使用到了随机初始化的字向量，使用者可以按需扩展为词向量，以及导入预训练的各类向量。

**Comment by agilelab** [comment]
> 实现这个目的是希望把它做成一套他人可以轻易扩展的文本分类框架，我这里仅作为baseline使用，保持它轻量化的宗旨。
> 
> 这个框架中已经使用到了随机初始化的字向量，使用者可以按需扩展为词向量，以及导入预训练的各类向量。

非常感谢您的恢复，我已参考尝试了字向量，效果还可以
