### ISSUE TITLE
embeding使用的是随机向量，可否用word2vec预先训练好的字向量作为embedding模型效果更好一些，请教一下作者为什么要用随机生成的字向量呢？

### ISSUE THREAD

**Issue by Paulliuliu** [gaussic/text-classification-cnn-rnn#141]
embeding使用的是随机向量，可否用word2vec预先训练好的字向量作为embedding模型效果更好一些，请教一下作者为什么要用随机生成的字向量呢？

**Comment by gaussic** [comment]
不是所有的模型，一开始就一定要导入1个训练好的词向量的。
完全可以从一个随机的向量开始，去训练一个符合特定任务的词向量。
要掌握两个概念，随机训练（training with random initialization) 和 微调（fine-tuning）。

建议初学者不要一上来就是word2vec，先掌握神经网络的基本概念。

**Comment by Paulliuliu** [comment]
非常感谢
