### ISSUE TITLE
运行完后的模型在哪呢？

### ISSUE THREAD

**Issue by rick29sz** [gaussic/text-classification-cnn-rnn#142]
可否单独加载呢？？

**Comment by gaussic** [comment]
请认真阅读run_cnn.py里面的test部分。

**Comment by flitdu** [comment]
> 请认真阅读run_cnn.py里面的test部分。
把训练集的类别改为3后，提示：
ValueError: Cannot feed value of shape (32, 10) for Tensor 'input_y:0', which has shape '(?, 3)'
 num_classes = 3  # 类别数
为何还会出现 10 呢？？

**Comment by flitdu** [comment]
@gaussic 把训练集的类别改为3后，提示：
ValueError: Cannot feed value of shape (32, 10) for Tensor 'input_y:0', which has shape '(?, 3)'
num_classes = 3 # 类别数
为何还会出现 10 呢？？

**Comment by rick29sz** [comment]
如下，验证集波动性很大，怎么回事呢？？
`Epoch: 9
Iter:    328, Train Loss:  0.014, Train Acc: 100.00%, Val Loss:    8.0, Val Acc:  50.00%, Time: 0:00:23 
Iter:    330, Train Loss: 3.7e-09, Train Acc: 100.00%, Val Loss:    4.8, Val Acc:  61.76%, Time: 0:00:23 
Iter:    332, Train Loss:   0.18, Train Acc:  96.88%, Val Loss:    2.8, Val Acc:  69.12%, Time: 0:00:23 
Iter:    334, Train Loss: 3.4e-08, Train Acc: 100.00%, Val Loss:    1.4, Val Acc:  83.82%, Time: 0:00:23 
Iter:    336, Train Loss: 1.5e-08, Train Acc: 100.00%, Val Loss:    1.1, Val Acc:  86.76%, Time: 0:00:23 
Iter:    338, Train Loss:   0.39, Train Acc:  93.75%, Val Loss:   0.95, Val Acc:  89.71%, Time: 0:00:24 
Iter:    340, Train Loss: 7.5e-09, Train Acc: 100.00%, Val Loss:   0.93, Val Acc:  86.76%, Time: 0:00:24 
Iter:    342, Train Loss: 7.4e-06, Train Acc: 100.00%, Val Loss:    1.5, Val Acc:  80.88%, Time: 0:00:24 
Iter:    344, Train Loss: 1.6e-05, Train Acc: 100.00%, Val Loss:    2.6, Val Acc:  67.65%, Time: 0:00:24 
Iter:    346, Train Loss:  0.004, Train Acc: 100.00%, Val Loss:    3.6, Val Acc:  61.76%, Time: 0:00:24 
Iter:    348, Train Loss: 3.2e-05, Train Acc: 100.00%, Val Loss:    4.4, Val Acc:  57.35%, Time: 0:00:24 
Iter:    350, Train Loss: 0.00024, Train Acc: 100.00%, Val Loss:    3.9, Val Acc:  58.82%, Time: 0:00:24 
Iter:    352, Train Loss: 0.00019, Train Acc: 100.00%, Val Loss:    1.5, Val Acc:  77.94%, Time: 0:00:24 
Iter:    354, Train Loss: 5.6e-07, Train Acc: 100.00%, Val Loss:   0.45, Val Acc:  92.65%, Time: 0:00:25 
Iter:    356, Train Loss:  0.069, Train Acc:  93.75%, Val Loss:   0.12, Val Acc:  91.18%, Time: 0:00:25 
Iter:    358, Train Loss:   0.35, Train Acc:  93.75%, Val Loss:   0.17, Val Acc:  92.65%, Time: 0:00:25 
Iter:    360, Train Loss: 3.7e-07, Train Acc: 100.00%, Val Loss:    1.1, Val Acc:  82.35%, Time: 0:00:25 
Iter:    362, Train Loss:   0.18, Train Acc:  96.88%, Val Loss:    2.5, Val Acc:  63.24%, Time: 0:00:25 
Iter:    364, Train Loss: 7.5e-09, Train Acc: 100.00%, Val Loss:    3.3, Val Acc:  55.88%, Time: 0:00:25 
Iter:    366, Train Loss: 3.7e-09, Train Acc: 100.00%, Val Loss:    3.9, Val Acc:  51.47%, Time: 0:00:25 
Iter:    368, Train Loss: 1.3e-08, Train Acc: 100.00%, Val Loss:    4.2, Val Acc:  50.00%, Time: 0:00:26`

**Comment by flitdu** [comment]
`
Epoch: 9
Iter:    328, Train Loss:  0.014, Train Acc: 100.00%, Val Loss:    8.0, Val Acc:  50.00%, Time: 0:00:23 
Iter:    330, Train Loss: 3.7e-09, Train Acc: 100.00%, Val Loss:    4.8, Val Acc:  61.76%, Time: 0:00:23 
Iter:    332, Train Loss:   0.18, Train Acc:  96.88%, Val Loss:    2.8, Val Acc:  69.12%, Time: 0:00:23 
Iter:    334, Train Loss: 3.4e-08, Train Acc: 100.00%, Val Loss:    1.4, Val Acc:  83.82%, Time: 0:00:23 
Iter:    336, Train Loss: 1.5e-08, Train Acc: 100.00%, Val Loss:    1.1, Val Acc:  86.76%, Time: 0:00:23 
Iter:    338, Train Loss:   0.39, Train Acc:  93.75%, Val Loss:   0.95, Val Acc:  89.71%, Time: 0:00:24 
Iter:    340, Train Loss: 7.5e-09, Train Acc: 100.00%, Val Loss:   0.93, Val Acc:  86.76%, Time: 0:00:24 
Iter:    342, Train Loss: 7.4e-06, Train Acc: 100.00%, Val Loss:    1.5, Val Acc:  80.88%, Time: 0:00:24 
Iter:    344, Train Loss: 1.6e-05, Train Acc: 100.00%, Val Loss:    2.6, Val Acc:  67.65%, Time: 0:00:24 
Iter:    346, Train Loss:  0.004, Train Acc: 100.00%, Val Loss:    3.6, Val Acc:  61.76%, Time: 0:00:24 
Iter:    348, Train Loss: 3.2e-05, Train Acc: 100.00%, Val Loss:    4.4, Val Acc:  57.35%, Time: 0:00:24 
Iter:    350, Train Loss: 0.00024, Train Acc: 100.00%, Val Loss:    3.9, Val Acc:  58.82%, Time: 0:00:24 
Iter:    352, Train Loss: 0.00019, Train Acc: 100.00%, Val Loss:    1.5, Val Acc:  77.94%, Time: 0:00:24 
Iter:    354, Train Loss: 5.6e-07, Train Acc: 100.00%, Val Loss:   0.45, Val Acc:  92.65%, Time: 0:00:25 
Iter:    356, Train Loss:  0.069, Train Acc:  93.75%, Val Loss:   0.12, Val Acc:  91.18%, Time: 0:00:25 
Iter:    358, Train Loss:   0.35, Train Acc:  93.75%, Val Loss:   0.17, Val Acc:  92.65%, Time: 0:00:25 
Iter:    360, Train Loss: 3.7e-07, Train Acc: 100.00%, Val Loss:    1.1, Val Acc:  82.35%, Time: 0:00:25 
Iter:    362, Train Loss:   0.18, Train Acc:  96.88%, Val Loss:    2.5, Val Acc:  63.24%, Time: 0:00:25 
Iter:    364, Train Loss: 7.5e-09, Train Acc: 100.00%, Val Loss:    3.3, Val Acc:  55.88%, Time: 0:00:25 
Iter:    366, Train Loss: 3.7e-09, Train Acc: 100.00%, Val Loss:    3.9, Val Acc:  51.47%, Time: 0:00:25 
Iter:    368, Train Loss: 1.3e-08, Train Acc: 100.00%, Val Loss:    4.2, Val Acc:  50.00%, Time: 0:00:26
`

**Comment by flitdu** [comment]
还有一个疑问，如何只预测一条数据呢？？？

**Comment by rick29sz** [comment]
你这到底能不能迁移？？？

**Comment by gaussic** [comment]
如果你是带着学习的心态来的，那我很乐意解答你的问题。
验证集的波动很大。不从各个层面找原因，来这里吐口水，这是傲慢和无理的，这也充分看出了你急于求成的表现。

这样的态度这里不欢迎，麻烦右转，谢谢。
