### ISSUE TITLE
报错Variable embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?

### ISSUE THREAD

**Issue by rfhzyx** [gaussic/text-classification-cnn-rnn#144]
你好，出现Variable embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?这个报错应该怎么修改代码结构？谢谢

**Comment by gaussic** [comment]
embedding只能创建一次，你是不是在用 notebook 或 spyder 之类的软件，保存了之前的结果
