### ISSUE TITLE
報錯問題

### ISSUE THREAD

**Issue by c91235a** [gaussic/text-classification-cnn-rnn#15]
你好
我在執行到
Training and evaluating...
Epoch: 1
之後運行過程中出現
File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (128, 8) for Tensor 'input_y:0', which has shape '(?, 10)'

我在train data換成8個分類，read_category、num_classes = 8 都已經更改了
请問怎麼解決這個問題？

謝謝

------------
另外
有時候還會出現
ValueError: Variable embedding already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)

請問要怎麼解決呢
感謝

**Comment by gaussic** [comment]
你好，按道理来说，如果修改了num_classes的话，这个input_y的shape肯定也是会修改的。

因为如下这三句：

```python
# 三个待输入的数据
self.input_x = tf.placeholder(tf.int32, [None, self.config.seq_length], name='input_x')
self.input_y = tf.placeholder(tf.float32, [None, self.config.num_classes], name='input_y')
self.keep_prob = tf.placeholder(tf.float32, name='keep_prob')
```

请确认在修改后有没有及时的保存，或者查找其他的问题。

关于第二个问题，可能是因为你在notebook或其他环境下运行，embedding层已经被定义过了，不能重复定义

```python
with tf.device('/cpu:0'):
    embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim])
    embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)
```

**Comment by c91235a** [comment]
以上的問題解決了!

請問有沒有直接在程式中寫入需要預測的一句話
不需要寫入分類和txt就能預測的方法

**Comment by gaussic** [comment]
你好，在这个repo中并未给出实现，但是可以基于`test()`函数修改而来：

首先读取保存的模型（模型的定义在`__main__`中）:

```python
session = tf.Session()
session.run(tf.global_variables_initializer())
saver = tf.train.Saver()
saver.restore(sess=session, save_path=save_path)  # 读取保存的模型
```

然后读取词汇表，并把需要处理的文本转换为数字id序列：

```python
words, word_to_id = read_vocab(vocab_dir)
data = [word_to_id[x] for x in content if x in word_to_id]
data = np.array(data)
```

再喂入模型中并运行：

```python
feed_dict = {
    model.input_x: data,
    model.keep_prob: 1.0
}
y_pred_cls = session.run(model.y_pred_cls, feed_dict=feed_dict)
```

以上就是基本的思路，未经调试，请自行增加其他代码。希望对比有帮助。

**Comment by c91235a** [comment]
你好
    print("Loading test data...")

    session = tf.Session()
    session.run(tf.global_variables_initializer())
    saver = tf.train.Saver()
    saver.restore(sess=session, save_path=save_path)  # 读取保存的模型

    content = "商標"
    words, word_to_id = read_vocab(vocab_dir)
    data = [word_to_id[x] for x in content if x in word_to_id]
    data = np.array(data)

    feed_dict = {
        model.input_x: x_test[start_id:end_id],
        model.keep_prob: 1.0}
    
    y_pred_cls = session.run(model.y_pred_cls, feed_dict=feed_dict)

運行這段code後出現報錯
name 'x_test' is not defined

請問該如何解決?

在下新手問題請見諒

**Comment by gaussic** [comment]
```python
feed_dict = {
    model.input_x: data,   # not x_test
    model.keep_prob: 1.0}
```

**Comment by c91235a** [comment]
你好
更改完後出現
ValueError: Cannot feed value of shape (2,) for Tensor 'input_x:0', which has shape '(?, 600)'

請問該如何處理?謝謝

**Comment by gaussic** [comment]
```python
def predict():
    config = TCNNConfig()
    categories, cat_to_id = read_category()
    words, word_to_id = read_vocab(vocab_dir)
    config.vocab_size = len(words)
    model = TextCNN(config)

    session = tf.Session()
    session.run(tf.global_variables_initializer())
    saver = tf.train.Saver()
    saver.restore(sess=session, save_path=save_path)  # 读取保存的模型

    content = "三星ST550以全新的拍摄方式超越了以往任何一款数码相机"
    data = [word_to_id[x] for x in content if x in word_to_id]
    data = kr.preprocessing.sequence.pad_sequences([data], config.seq_length)
    feed_dict = {
        model.input_x: data,
        model.keep_prob: 1.0
    }

    y_pred_cls = session.run(model.y_pred_cls, feed_dict=feed_dict)
    print(categories[y_pred_cls[0]])
```

你好，以上是predict()的完整实现，对于整个项目的一个理解，可能还需要完整地读一遍代码才能明白。

**Comment by c91235a** [comment]
謝謝你!我會再研究一下!

**Comment by gaussic** [comment]
不客气，希望对所有初学者都能有所帮助。

**Comment by Mryeshuai** [comment]
您好，请问我用的是像我自己爬下来的评论数据按照您的txt文件处理，像下面这样分三类，情感，内容和其他类：

情感	    不错哟。
情感     老师很厉害，加油！
情感     原来是这样的，老师指导的好，恍然大悟
情感     很有帮助
情感     哇 很有帮助
情感     不错哟
情感     是很有帮助
情感     对我很有帮助
情感     对电脑知识有很大的理解
情感     哇塞很有帮助

像这种类型的短文本是需要修改seq-length吗？跑起来以后出现如下错误：
The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Training and evaluating...
Epoch: 1
Traceback (most recent call last):
  File "run_cnn.py", line 188, in <module>
    train()
  File "run_cnn.py", line 97, in train
    s = session.run(merged_summary, feed_dict=feed_dict)
  File "/Users/yeshuai/Library/Python/3.5/lib/python/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/yeshuai/Library/Python/3.5/lib/python/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 1) for Tensor 'input_y:0', which has shape '(?, 10)'
请问是出现了哪方面的问题呢？初学者一枚，希望得到您的指导，谢谢了

**Comment by gaussic** [comment]
类似于这种非bug的问题，还请阅读代码。我这里并未提供一整套完整TensorFlow的教程。

**Comment by EdwardChan5000** [comment]
您好!
我的 config.num_classes = 2 的, 
`print y_pred_cls` 输出为: [1 1 0 1 1 0]
怎么理解? 
为什么第一个就是标签?
谢谢啦!!!

**Comment by gaussic** [comment]
@EdwardChan5000 这个应该是你前面出了问题，跟predict()无关，当只输入一篇文档的时候，y_pred_cls只会有一个输出的。

**Comment by alice1ma** [comment]
你好！
Spyder 下 train 成功执行完毕后，直接 test 时，报错  ValueError: Variable embedding already exists, disallowed.
这个 embedding 怎么重新使用呢，看了楼上的答案，实在没弄明白，
`with tf.device('/cpu:0'):
    embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim])
    embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)`
这里的定义怎么改呢？

**Comment by alice1ma** [comment]
你好！
Spyder 下 train 成功执行完毕后，直接 test 时，报错 ValueError: Variable embedding already exists, disallowed.
这个 embedding 怎么重新使用呢，看了楼上的答案，实在没弄明白，
with tf.device('/cpu:0'): 
    embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim]) 
    embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)
这里的定义怎么改呢？

**Comment by alice1ma** [comment]
你好！
Spyder 下 train 成功执行完毕后，直接 test 时，
报错 ValueError: Variable embedding already exists, disallowed.

这个 embedding 怎么重新使用呢，看了楼上的答案，实在没弄明白：

`with tf.device('/cpu:0'):
        embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim])
        embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)`

这里的定义怎么改呢？

**Comment by alice1ma** [comment]
你好！
Spyder 下 train 成功执行完毕后，直接 test 时，
报错 ValueError: Variable embedding already exists, disallowed.

这个 embedding 怎么重新使用呢，看了楼上的答案，实在没弄明白：

`with tf.device('/cpu:0'): 
       embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim]) 
       embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)`

这里的定义怎么改呢？

**Comment by alice1ma** [comment]
你好！
Spyder 下 train 成功执行完毕后，直接 test 时，
报错 ValueError: Variable embedding already exists, disallowed.

这个 embedding 怎么重新使用呢，看了楼上的答案，实在没弄明白：
`
with tf.device('/cpu:0'): 
      embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim]) 
      embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)
`
这里的定义怎么改呢？

**Comment by alice1ma** [comment]
你好！
Spyder 下 train 成功执行完毕后，直接 test 时，
报错 ValueError: Variable embedding already exists, disallowed.

这个 embedding 怎么重新使用呢，看了楼上的答案，实在没弄明白：

`
with tf.device('/cpu:0'):
       embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim]) 
       embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)

`

这里的定义怎么改呢？

**Comment by alice1ma** [comment]
你好！
Spyder 下 train 成功执行完毕后，直接 test 时，
报错 ValueError: Variable embedding already exists, disallowed.

这个 embedding 怎么重新使用呢，看了楼上的答案，实在没弄明白：

`
with tf.device('/cpu:0'):
      embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim])
      embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)

`

这里的定义怎么改呢？

**Comment by alice1ma** [comment]
你好！
Spyder 下 train 成功执行完毕后 test 时，
报错 ValueError: Variable embedding already exists, disallowed.

这个 embedding 怎么重新定义呢，看了楼上的帖子，实在没弄明白?
```
with tf.device('/cpu:0'):
    embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim])
    embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)
```

这里怎么修改呢？

**Comment by gaussic** [comment]
Spyder没用过，具体的请关掉程序，重新运行test。活着不要重新定义embedding，使用train的时候定义的embedding
