### ISSUE TITLE
可以增加个requirements.txt么

### ISSUE THREAD

**Issue by howie6879** [gaussic/text-classification-cnn-rnn#16]
你好 非常感谢作者的付出 一点小建议 可以把依赖包在requirements.txt列出来么😊

**Comment by gaussic** [comment]
谢谢你的建议，这个确实不太好加。因为TensorFlow在不同的操作系统上有不同的安装方式，并且分了CPU和GPU的区别。不过在README.md里面已经说明了一些相关的环境，只需要安装相应版本的TensorFlow和scikit-learn就可以了。

**Comment by howie6879** [comment]
恩恩 明白 不过readme那里少了scipy这个库 😊

**Comment by gaussic** [comment]
嗯，其实在装tensorflow的时候，它所依赖的所有库都会一并安装的，除了scikit-learn。

**Comment by howie6879** [comment]
我这里是装了 tensorflow 后 还提示 需要scipy
