### ISSUE TITLE
一点代码的建议以及问题

### ISSUE THREAD

**Issue by howie6879** [gaussic/text-classification-cnn-rnn#19]
你好:

1.关于在不同python版本的切换，我建议cnews_loader下的open_file改成这样，好处是不同版本下面运行模型不用人为改代码。

``` python
def open_file(filename, mode='r'):
    """
    Commonly used file reader, change this to switch between python2 and python3.
    mode: 'r' or 'w' for read or write
    """
    if sys.version_info[0] > 2:
        return open(filename, mode, encoding='utf-8', errors='ignore')
    else:
        return open(filename, mode)

```

2. 我在python3下训练出了一个消息分类模型，然后我编写测试，在同样的输入情况下，分别用python2和python3得到的结果不一样，比如输入十条垃圾消息[1,2,3,4]，python3运行这个脚本全部判断为垃圾消息，我用同样的模型，用python2运行，其中的几个会被判断为正常消息，不得其解，明明一样的模型，求指教，谢谢

**Comment by howie6879** [comment]
还是代码不兼容的问题，如下：
``` python
data = [self.word_to_id[x.encode('utf-8')] for x in content if x.encode('utf-8') in self.word_to_id]
```
不过在相同训练集情况下，确实python3下运行acc高点

**Comment by gaussic** [comment]
你好，关于python2效果不如3的情况，确实前面有不少人反馈。我个人排查可能问题出在数据读取的地方，因此在环境里只列举出了python3。所以如果要切换版本的话，光改一个open_file应该是不够的。由于我没什么在python2下编码的经验，所以就没做太大调整。有兴趣的话你可以试试，添加一个新的loader，然后提个pull request。
