### ISSUE TITLE
模型使用

### ISSUE THREAD

**Issue by Balabala125** [gaussic/text-classification-cnn-rnn#2]
您好，我还有一个问题，就是您这个只是一个训练模型的过程，但是您并没有把模型保存下来进行使用，对吧？其实就是关于这个模型已经训练好了，但是我有新打数据来洛，我该在哪儿对模型进行使用呢？
还有就是，那个词嵌入那儿，您使用的是什么方法呢？word2vec，还是one-hot呀？那里没太看懂，谢谢！！

**Comment by gaussic** [comment]
模型保存与使用可以，但是需要更多的代码。embedding层随机初始化了一个[vocab_size,embedding_dim]的矩阵，训练时会更新这个矩阵，相当于训练完词向量也就有了。要多读论文。

**Comment by Balabala125** [comment]
好的，谢谢您啦
