### ISSUE TITLE
tensorflow-gpu加速问题

### ISSUE THREAD

**Issue by fight12** [gaussic/text-classification-cnn-rnn#25]
我在运行python run_rnn.py train时，非常慢，可不可用tensorflow-gpu进行加速运算？怎么修改？谢谢！

**Comment by gaussic** [comment]
如果有GPU，且安装了tensorflow-gpu的话，直接就会进行加速，不需要修改代码

**Comment by fight12** [comment]
![1212](https://user-images.githubusercontent.com/29722359/36640819-ee2463f2-1a60-11e8-9267-ae3d10eaf3bc.jpg)
像我这种耗时十多个小时这么长时间，是我电脑的问题吧，
![321](https://user-images.githubusercontent.com/29722359/36640834-507b5a24-1a61-11e8-9632-ed3569543e81.jpg)
还有我安装tensorflow-gpu了，也安装了CUDA和CUDNN了，而且测试后都显示安装成功了，可是运行后时间并没有减少，这是什么原因？

**Comment by gaussic** [comment]
这个就不清楚了，应该是其他的原因，是否有对代码做其他修改

**Comment by fight12** [comment]
谢谢，找到原因了，是我电脑的问题。

**Comment by Doflamingio** [comment]
您好，我也遇到了一样的问题，GPU利用率一直很低，最高也就17%，另外CPU一直在75%左右，也不高；
我的配置应该是对的，因为我跑过其他模型，两个GPU都可以跑满；
我没有改代码，数据也是用的你提供的，我的环境配置如下：
CUDA Version 10.1.243
CUDNN 7.6.3
tensorflow-gpu 1.14.0

我曾尝试以下方法，都不起作用
1.增大batch-size:512
2.手动指定GPU： os.environ["CUDA_VISIBLE_DEVICES"] = "1"
3.指定GPU利用率为0.8（config.gpu_options.per_process_gpu_memory_fraction = 0.8）

是模型本身就不需要很高的GPU吗，不太懂原理，希望得到您的帮助，谢谢
