### ISSUE TITLE
不使用字符级别的将如何修改

### ISSUE THREAD

**Issue by xiximeng** [gaussic/text-classification-cnn-rnn#28]
初学者想请教下，您的程序是使用了字符级的CNN（Character-level Convolutional Networks for Text Classification），请问若是想实现Convolutional Neural Networks for Sentence Classification论文中的实验，应该如何进行修改呢？

**Comment by gaussic** [comment]
http://www.wildml.com/2015/12/implementing-a-cnn-for-text-classification-in-tensorflow/
看这个吧

**Comment by xiximeng** [comment]
再请教下，对于中文来讲基于字符的CNN是不是就是利用单个字训练的词向量，而不基于字符的是通过jieba等方法分词后训练得到的词向量呢？两者后续的处理都是一样的，是吗？

**Comment by gaussic** [comment]
对，没有太大区别

**Comment by xiximeng** [comment]
感谢指导，豁然开朗
