### ISSUE TITLE
运行报错问题，还望您指点

### ISSUE THREAD

**Issue by MeaninglessAI** [gaussic/text-classification-cnn-rnn#3]
您好，我下载你的代码在自己电脑上运行。你的代码风格很好，让人看着不累，层次清楚，很舒服。
   但我在运行你的run_epoch.py 文件时，出现了以下错误信息:

![tim 20170907094616](https://user-images.githubusercontent.com/23152242/30142092-81bb70f6-93b1-11e7-9673-3dac9a22a6d7.png)
  报错信息显示是由下面这条语句引起的：
    inputs = tf.nn.embedding_lookup(embedding, self.input_x)

我觉得可能的原因：
  因为我自己改变了数据集，用的我自己的数据。一共就2000条，两个类别。所以可能是原来 configuration.py  文件中的vocab_size  参数不符合我自己的情况，原来vocab_size =5000 ,感觉比较大。
但我不知道该到多少合适（刚入门）。

希望您有空能指点一下。万分感谢

**Comment by gaussic** [comment]
@yangjinray 你好，出现这个问题应该是你的process_file()生成的数据超过了vocab_size的界限。
在run_epoch.py中有这样一句：

```
if not os.path.exists('data/cnews/vocab_cnews.txt'):
    _build_vocab('data/cnews/cnews.train.txt')
```

这个构建词汇表的函数是可以传入一个vocab_size的，你试着把它改小。
另外，在模型配置时，vocab_size是根据词汇表文件大小来的。

```
config = TRNNConfig()
config.vocab_size = len(words)
model = TextRNN(config)
```

你可以尝试这调试这两块，查看一下你的词汇表文件到底有多少个词汇。在代码中多加几个print，输出中间结果，看看到底是哪里出现了问题。

不用着急，慢慢调试，希望对你有帮助。

**Comment by MeaninglessAI** [comment]
真的感谢你的耐心解答，按照你说的我改了，在mac上可以运行了。但又出现了新问题，当我在windows上运行相同的代码时，会出现下列问题:
  0. 当我在  tf.device('/cpu:0'):   改为 tf.device('/gpu:0'):  后，代码可以运行，但是输出结果一直不变，如下图所示。
  
![image](https://user-images.githubusercontent.com/23152242/30158541-2bfc1cd2-93f8-11e7-8f86-bf55fe9d17e8.png)

不知道为什么会出现上面的结果，但是我在mac上运行时（cpu模式），输出结果很正常（虽然精度不够），就像下面这样， 结果是很正常的。
![image](https://user-images.githubusercontent.com/23152242/30158865-33ac3358-93f9-11e7-89b3-d6d68158907d.png)


在windows上以gpu模式上运行时，虽然如上面所说一样没报错，但结果不变。还有一个不对的地方是，
本该生成词汇的vocab_cnews.txt文件一直为空，但没报错。


1. 当在windows上面以cpu模式运行时，与gpu同样的代码，却会出现以下错误:
  
![image](https://user-images.githubusercontent.com/23152242/30158750-ceabd904-93f8-11e7-91e0-8b3c864b5cd6.png)

报错信息显示还是由 _inputs = tf.nn.embedding_lookup(embedding, self.input_x)  这句话引起的。
难道cpu计算和gpu计算对代码还有影响？


希望你有空指点一下。

**Comment by gaussic** [comment]
@yangjinray 
1.  不能将tf.device('/cpu:0'): 改为 tf.device('/gpu:0'): ，在官方的文档中embedding层是固定在cpu上面运行的，在gpu上面会存在问题。
2. 我刚刚测试了以下windows下面的问题，环境是python 3.5 和 tensorflow 1.3。你的问题是在之前的运行过程中报了错，因为编码的一些问题，但是仍然生成了vocab.txt文件，但是这个vocab文件是空的，导致没有读取到词汇，因而后面的代码报了这个错。python3中，需要在所有的open文件操作里面加上encoding='utf-8'这个参数。
希望能帮到你。

PS：我做了一些关于python3的调整，建议拉取新的代码。

**Comment by MeaninglessAI** [comment]
好的，我重新下一个试试。谢谢了，还有很多很多问题想请教你。等我仔细研究一下代码再来打扰。感谢
