### ISSUE TITLE
使用bash文件生成数据的时候错误

### ISSUE THREAD

**Issue by xiximeng** [gaussic/text-classification-cnn-rnn#30]
请问，我在使用copy_data.sh在每个分类拷贝6500个文件的时候，终端总是出现“copy_data.sh: 25: copy_data.sh: let: not found”，刷屏出现，
并且每个文件夹下面生成的文件数远远超过6500个，请问是为什么呢

**Comment by gaussic** [comment]
最好不用sh文件，那个是我在mac下随便写的，你可以写个py脚本来拷

**Comment by xiximeng** [comment]
好的，谢谢
