### ISSUE TITLE
同一类的召回率怎么算的？

### ISSUE THREAD

**Issue by saladfox** [gaussic/text-classification-cnn-rnn#32]
为什么同一类的准确率和召回率不一样？就比如你cnn的运行结果，财经类准确率96，召回率99

**Comment by gaussic** [comment]
建议百度下准确率和召回率

**Comment by saladfox** [comment]
TP: 将正类预测为正类数  40
FN: 将正类预测为负类数  20
FP: 将负类预测为正类数  10
TN: 将负类预测为负类数  30
准确率= 预测对的/所有 = (TP+TN)/(TP+FN+FP+TN) = 70%
精确率= TP/(TP+FP) = 80%
召回率= TP/(TP+FN) = 2/3
请问您的运行结果中的precision是准确率还是精确率？如果是准确率，按照定义，同一类中准确率和召回率应该是相等的，感谢您的回复

**Comment by gaussic** [comment]
accuracy: 准确率
precision: 精确率
recall: 召回率

以财经类为例：
precision: 992 / (992 + 1 + 14 + 9 + 16 + 4) =0.96   混淆矩阵一列
recall: 992 / (992 + 2 + 1 + 5) = 0.99    混淆矩阵一行
accuracy: 是对整个数据集统计的，不算单个类

**Comment by saladfox** [comment]
非常感谢！
