### ISSUE TITLE
关于cnews.test.txt

### ISSUE THREAD

**Issue by janetat** [gaussic/text-classification-cnn-rnn#34]
把cnews.test.txt中只置换为一条科技新闻
![screenshot from 2018-03-02 16-47-30](https://user-images.githubusercontent.com/5557194/36890601-88a43e26-1e39-11e8-8115-96dfe2c8cfa1.png)

python run_cnn.py test 进行训练 给出的结果是体育。
![screenshot from 2018-03-02 16-47-36](https://user-images.githubusercontent.com/5557194/36890626-97df8058-1e39-11e8-8b1e-45634cb76617.png)

再添加其他类别的新闻:
![screenshot from 2018-03-02 16-50-16](https://user-images.githubusercontent.com/5557194/36890738-fd8e71c0-1e39-11e8-80dc-c84d5666174a.png)
![screenshot from 2018-03-02 16-50-23](https://user-images.githubusercontent.com/5557194/36890739-fddfb724-1e39-11e8-9813-edc76a074b0a.png)

我是个新手，在这上面挺困惑的

**Comment by gaussic** [comment]
这个repo里面没有包含训练好的模型，因此需要使用数据集先进行训练，然后再使用测试方法进行测试。

**Comment by janetat** [comment]
@gaussic 作者你好。。。可是我已经训练CNN了，用了一个半小时，之后出现了这个情况

**Comment by gaussic** [comment]
这个问题我也不好给你debug，再查查哪里有什么问题

**Comment by janetat** [comment]
@gaussic thanks
