### ISSUE TITLE
请教一下数据量的问题

### ISSUE THREAD

**Issue by JayJQK** [gaussic/text-classification-cnn-rnn#35]
我现在使用做五类的分类，每一类的数据大概1500条，请问多少数据量适合使用CNN和RNN分类，因为除了五类之外，还有一些数量少的类我也想进行分类，求教了

**Comment by gaussic** [comment]
你可以先放进去试试看效果

**Comment by JayJQK** [comment]
还有一个问题想请教您，就是这个项目都可以在哪些方面进行改进，我想以此写我的毕业论文，谢谢了

**Comment by gaussic** [comment]
改进的点很多，换模型，换网络，换数据集等等

**Comment by JayJQK** [comment]
我是想基于CNN和RNN来进行，而且数据集是依托在中医的数据上，我的意思是可不可以把字向量改成词向量，加入中文分词，调参数这些方面，除了这些还有什么，谢谢了

**Comment by gaussic** [comment]
1. 改词向量是很简单的事情，修改数据处理部分
2. CNN和RNN虽然是单独的模型，但是也是可以结合的
3. 调参是根据模型来的，现在的参数在Config里面

**Comment by JayJQK** [comment]
特别感谢您
