### ISSUE TITLE
奇怪的问题

### ISSUE THREAD

**Issue by xiximeng** [gaussic/text-classification-cnn-rnn#36]
之前将您的代码改为了14类，也就是全部的数据集，保证其他的地方都修改正确，后来又改回了10类，但是这次忘记在代码中去掉原来的多余的四类了，也就是在read_category中的categories中还是14个类（cnews下面的数据集放的是10个类），程序运行的结果是只选取了categories这个list中的前10个类，没有后四个，而且对于没有数据集的类别的准确率竟然也高达90%，请问这是什么情况呢？不知道我描述清楚没

**Comment by gaussic** [comment]
认真研究研究数据处理这一块，应该不影响的
