### ISSUE TITLE
模型使用

### ISSUE THREAD

**Issue by qumj** [gaussic/text-classification-cnn-rnn#4]
您好！请教一下，请问cnews_loader.py中的to_words方法是怎么使用的呢。我插入参数content和words报错。我看您代码里只是训练了模型，请问模型训练保存起来后，后面是怎么使用这个模型的呢?
麻烦您了，谢谢！

**Comment by gaussic** [comment]
to_words是将id表示的内容转换为原始的文字，content 是一个id的列表，words是文字的列表。

关于模型的保存，我在 [TENSORFLOW(4) - 保存/恢复/提前终止](https://gaussic.github.io/2017/08/15/tensorflow-saver/)一文中做了阐述，只需要加入部分的代码即可完成。

**Comment by qumj** [comment]
好的，谢谢啦，我再研究一下代码，有问题再请教您。谢谢

**Comment by qumj** [comment]
您好！再麻烦请教一下，我运行代码时在文件转id部分一直出错
 label_id.append(cat_to_id[labels[i]])   这一行一直下标越界。
（数据是直接下载用的，没有截取过6500条，不知道有没有影响）

**Comment by gaussic** [comment]
```
def _read_category():
    """读取分类目录，固定"""
    categories = ['体育', '财经', '房产', '家居',
        '教育', '科技', '时尚', '时政', '游戏', '娱乐']
    cat_to_id = dict(zip(categories, range(len(categories))))
```
在这个代码中，类别是固定的，要根据你的数据集进行调整，用到哪些类就调整为哪些类，当然你也可以修改代码，自行调整这些累。

**Comment by qumj** [comment]
14个类我都写上了，可能是循环的时候i不一样content[i]和 labels[i]不一样，下标就越界了

 for i in range(len(contents)):
        data_id.append([word_to_id[x] for x in contents[i] if x in word_to_id])
        label_id.append(cat_to_id[labels[i]])

**Comment by gaussic** [comment]
说明你的数据处理需要调整，你把中间的部分结果输出来，比如把`print(labels[i])`输出来看看

**Comment by qumj** [comment]
嗯嗯，我再找找。谢谢啦！

**Comment by qumj** [comment]
不好意思啦，还得麻烦您一下！训练模型的时候有个错误。运行了3个多小时了，报错
cannot feed value if shape(1,1) for Tensor 'input_y:0',which has shape‘(？，14)‘
指向行是  s =session.run(merged_summary, feed_dict=feed_dict)。
发现 file_to_ids()方法打印出的y_pad只有这[[1]]一个值,打印label_id也只有一个[0]

**Comment by gaussic** [comment]
仔细阅读代码

```
    # 使用keras提供的pad_sequences来将文本pad为固定长度
    x_pad = kr.preprocessing.sequence.pad_sequences(data_id, max_length)
    y_pad = kr.utils.to_categorical(label_id)  # 将标签转换为one-hot表示
```

label_id 中的所有编码是从0开始的。这一段把y编程了one-hot表示，你把他们输出来试试。

**Comment by qumj** [comment]
嗯，我把y_trian打印出来看了一下，就这一个结果[[1.]]。10个分类，不应该是10个吗.
