### ISSUE TITLE
深度学习问题

### ISSUE THREAD

**Issue by fight12** [gaussic/text-classification-cnn-rnn#40]
利用深度学习CNN做中文文本分类与别的文本分类方法的根本区别在哪？是不是在文本特征表示这里？其余部分是不是跟以前的分类方法相同？

**Comment by gaussic** [comment]
你好，这里只提供使用深度学习做文本分类的 TensorFlow 实现，不提供系统化的教程。

详细的方法请参考论文，详见 README.md。

有关深度学习在自然语言处理领域的应用，请使用搜索引擎搜索。
