### ISSUE TITLE
关于stop words

### ISSUE THREAD

**Issue by janetat** [gaussic/text-classification-cnn-rnn#42]
这个程序貌似没有stop words。。。通过词汇表看出来。。
但是为啥分类效果还这么好

**Comment by gaussic** [comment]
这是深度学习的方法，直接从原始数据自动学习特征，可以不需要停用词，甚至不需要分词。

**Comment by janetat** [comment]
哈哈是呢，我查了相关的资料和论文也是这样子的
CNN最大优点就是自动特征提取
Thx
