### ISSUE TITLE
词汇表问题

### ISSUE THREAD

**Issue by Solwarda** [gaussic/text-classification-cnn-rnn#45]
请问一下：您所用的词汇表都是基于训练集的，测试集中没有出现的词或者字符怎么办？我看到代码中是不在训练集的词或者字符不参与计算。这样的是否符合常理呢？

**Comment by gaussic** [comment]
嗯，符合常理

**Comment by Solwarda** [comment]
是的。能不能将测试集中的词加入词库呢？或者训练更庞大的词向量呢

**Comment by gaussic** [comment]
可以，可以。

**Comment by Solwarda** [comment]
恩恩，正在学习您的代码，感谢

**Comment by Solwarda** [comment]
还请问下，您这个是字符级别的，把每句话切分成汉子字符了，不涉及分词吧？

**Comment by gaussic** [comment]
不涉及，分词的话可考虑结巴等分析工具
