### ISSUE TITLE
请问您的词向量表是怎么生成的？

### ISSUE THREAD

**Issue by xuwuW** [gaussic/text-classification-cnn-rnn#48]
embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim])
这里并没有指定它的初始化方式，请问它的值从何而来？

**Comment by gaussic** [comment]
https://www.tensorflow.org/api_docs/python/tf/get_variable


If initializer is None (the default), the default initializer passed in the variable scope will be used. If that one is None too, a glorot_uniform_initializer will be used. The initializer can also be a Tensor, in which case the variable is initialized to this value and shape.


多查文档。。

**Comment by xuwuW** [comment]
谢谢您！打扰您了。获益良多。
