### ISSUE TITLE
训练与测试的区分

### ISSUE THREAD

**Issue by wangtao1321** [gaussic/text-classification-cnn-rnn#5]
您好！我是tensorflow的新手，我在模型的源码中没有看到对训练和测试过程的区分，例如测试仍旧使用了dropout，请问这个模型中如何设置一个flag使测试时网络结构改变（例如测试时不使用dropout）
ps：我自己想的办法是定义一个全局变量is_train，不过不知道您是否有其他考虑不区分训练和测试

**Comment by gaussic** [comment]
你好，同新手。对于dropout看来我还是不太理解，我这边修正一下代码重新运行，希望对你会有一定的帮助。

**Comment by gaussic** [comment]
fixed
