### ISSUE TITLE
一个疑问

### ISSUE THREAD

**Issue by ArminSuper** [gaussic/text-classification-cnn-rnn#50]
在cnn_model.py 中gmp = tf.reduce_max(conv, reduction_indices=[1], name='gmp')
请问这行可以实现 global max pooling layer吗？这个不是Computes the mean of elements across dimensions of a tensor吗？看了dennybritz写的，用了tf.nn.max_pool。麻烦您给解答，拜托了。

**Comment by gaussic** [comment]
第一，tf.reduce_max的官方文档描述：

```
Computes the maximum of elements across dimensions of a tensor. (deprecated arguments)
```

详见：https://www.tensorflow.org/api_docs/python/tf/reduce_max

第二，这里实现的模型和dennybritz以及论文是不一样的，它更加接近于[Keras的imdb_cnn.py](https://github.com/keras-team/keras/blob/master/examples/imdb_cnn.py)样例，所以无法拿两者进行比较。

**Comment by ArminSuper** [comment]
谢谢您的解答
