### ISSUE TITLE
文本分类要分100类，这个模型适合吗

### ISSUE THREAD

**Issue by Rokie-33** [gaussic/text-classification-cnn-rnn#52]
本人文本分类新手，在做一个企业类型分类的项目，通过企业的经营范围把企业分为20个大类，97个小类，每个大类中包含几个小类，请问使用哪种模型会比较好呢？试过svm，因为使用的是libsvm，多分类时要有k*(k-1)/2个模型，感觉代价太大，只做了20大类的分类

**Comment by gaussic** [comment]
只要数据量大，只要计算量足，用深度学习分10000个类都不是问题。

**Comment by kifish** [comment]
个人认为，若数据量很小，例如每个类别的样本数是仅有几十，那么用svm,softmax这种模型比较好。若数据量中等，用xgboost这种模型比较好。如果数据量足够多，则用深度学习。

**Comment by Rokie-33** [comment]
非常感谢，已经做了初步的运行，但是效果还不是很好，优化中

**Comment by coleyangsecure** [comment]
@Rokie-33 你好，我也在做同样的项目，用企业经营范围进行国标行业分类。可以聊聊。

**Comment by Rokie-33** [comment]
@coleyangsecure 可以呀，我现在使用这个模型进行了20个大类分类，准确率只有85%，并且数据都是现爬的，有点不够用，你用的什么数据呀

**Comment by coleyangsecure** [comment]
@Rokie-33 加我qq说吧，342674595
