### ISSUE TITLE
cnn层数的问题

### ISSUE THREAD

**Issue by JayJQK** [gaussic/text-classification-cnn-rnn#54]
你好，请问这个模型是用了几层cnn来实现的

**Comment by gaussic** [comment]
Read the code plz!!!

**Comment by JayJQK** [comment]
看代码 是只用了一层实现，但是我看基于字符的cnn论文里是采用了9层 就是6层cnn加上3层全连接层，是这样的么

**Comment by gaussic** [comment]
Reade README plz!!!
