### ISSUE TITLE
长文本迁移到短文本的效果问题

### ISSUE THREAD

**Issue by 34127chi** [gaussic/text-classification-cnn-rnn#55]
想把lz的长文本分类模型，迁移到到项目的短文本分类上，lz有试过吗？

**Comment by gaussic** [comment]
不会有什么问题，把 seq_length 调小来，多调调参就可以了。

**Comment by 34127chi** [comment]
问题在于项目语料少 所以想利用迁移学习 但我这边又是短文本

**Comment by blueskydavie** [comment]
如果迁移到短文本，都调整哪些参数呢？调整到多少比较合适呢？ 我把seq_length调小了，卷积核尺寸kernel_size调整为了3.

**Comment by 34127chi** [comment]
迁移个人认为是迁移在 源 所学习到的权重等等。把seq_length等调参数以适用于你现在的项目，顶多算套用网络框架，具体参数选择就是寻优吧，像grid serach、random search、Bayesian optimization-based search

**Comment by 34127chi** [comment]
> 如果迁移到短文本，都调整哪些参数呢？调整到多少比较合适呢？ 我把seq_length调小了，卷积核尺寸kernel_size调整为了3.

迁移个人认为是迁移在 源 所学习到的权重等等。把seq_length等调参数以适用于你现在的项目，算套用网络框架，具体参数选择就是寻优吧，像grid serach、random search、Bayesian optimization-based search

**Comment by rainystef** [comment]
请问从长文本迁移到短数组类型数据 改方法是否可行

**Comment by 34127chi** [comment]
> 请问从长文本迁移到短数组类型数据 改方法是否可行

短数组类型数据？这个是textcnn实现 建议看下论文
