### ISSUE TITLE
求教：尝试做1000个类别的分类，发现只有700的类别分出，有300缺失，可能是什么原因啊？

### ISSUE THREAD

**Issue by muzier** [gaussic/text-classification-cnn-rnn#58]
如题。
先给作者的代码点个赞，尝试了一下短文本的效果也不错，进一步希望扩大分类的数量，所以搞了1000个类别进行测试，但是发现执行test之后的结果里只显示了700个类别的准确率、召回率，有300个类别没有显示出来，这可能是什么造成的啊？另外就是tensorboard目录下只有events.out.tfevents.xxxx 的输出，执行tensorboard --logdir之后提示并没有找到输出文件，是不是对tensorboard的输出不完整啊？先谢过啦 @gaussic

**Comment by muzier** [comment]
再补充个问题：发现调整vocab_size的大小好像对训练得到的 vocab.txt 里面字典数并没有太大影响，我调大了之后生成的字典数总是在3000左右，这可能是和我训练的语料领域本身有关么？另外如果用word2vec训练出词向量再进行CNN训练的话，效果是不是比字典表更好啊？

**Comment by gaussic** [comment]
第一个问题，可能是你的测试集类别不够，仔细读一下数据处理部分。

第二个问题，如果你的词汇表里面并没有 5000 个词，那就以你最大的词数作为 vocab_size，还是要详读数据处理部分。
