### ISSUE TITLE
Convolutional Neural Networks for Sentence Classification

### ISSUE THREAD

**Issue by MeaninglessAI** [gaussic/text-classification-cnn-rnn#6]
请问一下，您的这个代码是基于 Yoon Kim的论文《Convolutional Neural Networks for Sentence Classification》 实现的吗？

**Comment by gaussic** [comment]
不是，论文中采用了多种卷积核的操作，相对来说过于复杂，只使用一种卷积核就已经可以达到较好的效果了。

当然如果需要修改的话，把conv1d换几个kernel_size，然后merge一下就可以了，改起来还是挺简单的。

**Comment by MeaninglessAI** [comment]
谢谢您的回答，我还想请教一下，我在实际运行的过程中，发现每次基本每次都是过拟合。就像下面这样
  
![tim 20171011124037](https://user-images.githubusercontent.com/23152242/31422635-bad93eb4-ae81-11e7-9c8f-43c4f63c87fa.png)

我自己的问题是个二分类的问题，数据集大小在1w左右。自己在参数配置里面也改过几次，结果每次都是过拟合，不知道该从哪方面入手调节参数，还请指点一二。谢谢

**Comment by gaussic** [comment]
过拟合的原因可能有很多种，包括数据的和模型的。
- 除了调试配置里面的参数，还可以调整网络的结构，比如再加一层卷积层。
- 鉴于你的数据量只有1万左右，你要分析分析句子的最大、最小以及平均长度，取多大的seq_length合适。
- 根据你的数据集，查看一下取多大的vocab_size合适。
- 此外，这个代码是字符集的CNN网络，中文的文本分类还可以引入分词（比如jieba），然后基于词进行CNN分类。
最主要的问题还是在于数据，要学会充分的分析数据。

**Comment by MeaninglessAI** [comment]
好的，谢谢。我试一试

**Comment by MeaninglessAI** [comment]
再请问一下下，就是你的代码中还有RNN的实现，具体有两种方式 lstm 和 gru ，我想问一下，这两种实现是你自己写的吗？还是向CNN一样，参考了一些论文和资料。谢谢解答。我想了解一下

**Comment by gaussic** [comment]
RNN模型是非常常见的实现，就是多层的RNN网络接全连接层，这个在网上有非常多的资料。我这边主要是参照tensorflow的rnn的api来写的。

在我的博客 [深度神经网络训练IMDB情感分类的四种方法](https://gaussic.github.io/2017/03/03/imdb-sentiment-classification/)中也做了多种文本分类算法的实现，不过是基于Keras的，可供参考。

**Comment by MeaninglessAI** [comment]
好的，谢谢分享

**Comment by MeaninglessAI** [comment]
请问一下，刚才代码还能正常运行，但是我稍微改了一下 cnews_group.py这个代码，
，为了以示区别，我重新改了一下cnews_group.py 这个文件的名字（这两个地方是我唯一改过的地方）， 随后我运行改过后的cnews_group.py这个程序，能正常运行，但运行run_epoch.py, 却报下面的错误，我抠破脑袋也没找到错误， 
![snipaste_2017-10-11_19-02-51](https://user-images.githubusercontent.com/23152242/31437173-fbe0dd7e-aeb6-11e7-9911-a5f6c5b6b6ab.png)

图中显示这条语句报错，s = session.run(merged_summary, feed_dict=feed_dict) ，我觉得应该是 feed_dict的错误，就顺着往上找，feed_dict是由这句feed_dict, _ = feed_data(batch)， 我然后又看batch的
问题，继续往上找，batch 来自这一句  for i, batch in enumerate(batch_train): ，然后我又看batch_train的问题， batch  来自这一句  batch_train = batch_iter(list(zip(x_train, y_train)),
        config.batch_size, config.num_epochs)，

我觉得有两种可能，一种是config.batch_size 这个参数的问题，但这个我并没有在configuration.py 文件中改过它。一直都没改过。应该不会出错。configuration.py  里面batch_size = 128 。

另外一种这可能是，batch_iter函数的问题，然后我又往上找，发现batch_iter 来自cnews_loader.py 这个文件，定义如下：
![-21](https://user-images.githubusercontent.com/23152242/31437654-90ff75fe-aeb8-11e7-8a69-92bfc1c8c22e.png)

直到这里，我还是没发现问题。
还望指教。

**Comment by MeaninglessAI** [comment]
不用了，真不好意思。 我写完这个之后，回去发现，自己手贱，把cnews_group.py文件中的count=0 位置改了，麻烦了。

**Comment by luoyexuge** [comment]
是否可以写预测的方法？

**Comment by MeaninglessAI** [comment]
预测的方法？什么意思啊

**Comment by gaussic** [comment]
在 model 里面有 pred_y，你只要稍微修改代码，使用 
```python
predicted = sess.run(model.pred_y, feed_dict)
```
feed_dict的batch为1就可以了。

**Comment by MeaninglessAI** [comment]
请问如果这个要加入正则化，怎么该呢？我查了资料， 加入正则化，有两步。
1. 创建一个正则方法(函数/对象) 
2. 将这个正则方法(函数/对象),应用到参数上

第一步：
tf.contrib.layers.l1_regularizer(scale, scope=None)

返回一个用来执行L1正则化的函数,函数的签名是func(weights). 
参数:
scale: 正则项的系数.
scope: 可选的scope name

第二步：
应用正则化方法到参数上
tf.contrib.layers.apply_regularization(regularizer, weights_list=None)

先看参数

regularizer:就是我们上一步创建的正则化方法
weights_list: 想要执行正则化方法的参数列表,如果为None的话,就取GraphKeys.WEIGHTS中的weights.

我现在不知道第二步该加到那里？感觉找不到参数啊？是该cnn_model.py 这个文件里面的吗？

请指点一下，谢谢。

**Comment by gaussic** [comment]
这个问题就不在这个项目的范围内了，需要你自己好好地研究文档然后再进行修改。加油。

**Comment by MeaninglessAI** [comment]
好的，谢谢。

**Comment by A11en0** [comment]
请问vocab_size对分类影响大吗？我直接设置成数据集词表大小不是更好吗？
