### ISSUE TITLE
验证数据不应该是拿一篇文章,然后输出这篇文章输入哪个分类吗？

### ISSUE THREAD

**Issue by dapsjj** [gaussic/text-classification-cnn-rnn#61]
我看这几个文本文件cnews.test.txt，cnews.train.txt，cnews.val.txt，cnews.vocab.txt全部都有分好类的标签在每一行的开头，那么我想测试一篇文章比如，我有一个叫“mytxt.txt”的记事本，里面有一句话，500字，那么我想测试这个“mytxt.txt”属于哪个分类，应该怎么做？

**Comment by gaussic** [comment]
predict.py

**Comment by dapsjj** [comment]
谢谢！
