### ISSUE TITLE
请问验证的准确率基本不提高，应该如果和调整参数?

### ISSUE THREAD

**Issue by vaxilicaihouxian** [gaussic/text-classification-cnn-rnn#63]
![image](https://user-images.githubusercontent.com/8603593/40831161-d79c370e-65ba-11e8-88e8-c995d26435e3.png)

修改了分类数目为2，对应的名字改成了自己的分类名称
数据集用了自己的文件，调用helper下的脚本生成了相应的训练、验证需要的文件

目前改了
num_classes = 2 (原来是10)
seq_length = 200 (原来是500)

**Comment by gaussic** [comment]
config 里面的参数都可以调，准确率不高可能是数据本身的问题

**Comment by vaxilicaihouxian** [comment]
感谢您的回答 @gaussic 
另外，predict.py是提供了cnn的预测使用方法，能否提供rnn的呢？
