### ISSUE TITLE
cnews_group 的問題

### ISSUE THREAD

**Issue by AnselmSu** [gaussic/text-classification-cnn-rnn#66]
大神你好
編譯環境為 windows10與 ubuntu16.04，執行cnews_group 後data/cnewn所分類出來的檔案都是為0位元
跑完後也只跑出
![image](https://user-images.githubusercontent.com/23737897/41222673-31a42acc-6d9a-11e8-91ad-2fafab0c66ef.png)

想請問這是什麼問題?  (謝謝

**Comment by gaussic** [comment]
cnews_group.py 只对 python 3 适用，如果需要使用 python 2，需要对代码的文件读取与写入进行修改。

**Comment by AnselmSu** [comment]
喔 不好意思忘記補上，是用 Python3.4.6+TF1.8版本。
我先行檢查文件看看，謝謝:)

**Comment by AnselmSu** [comment]
已經解決問題搂  感謝 👍
