### ISSUE TITLE
ValueError: Cannot feed value of shape (0, 46) for Tensor 'input_y:0', which has shape '(?, 10)'

### ISSUE THREAD

**Issue by albertyou2** [gaussic/text-classification-cnn-rnn#69]
@gaussic

你好我在运行代码的时候碰到这个问题
ValueError: Cannot feed value of shape (0, 46) for Tensor 'input_y:0', which has shape '(?, 10)'

我把类别改成了我我的数据，同时修改了模型的餐素，运行出错
有可能是什么问题？谢谢！

**Comment by tak-wah** [comment]
cnn_model.py 里的 num_classes 参数调了吗？

**Comment by tak-wah** [comment]
cnew_loader.py 脚本里的 categories 变量修改了吗？
cnn_model.py 脚本里的 num_classes 参数调了吗？

**Comment by shulizangyujing** [comment]
请问你的问题解决了吗，我也遇到了同样的问题

**Comment by yichengye310** [comment]
请问你的问题解决了吗，我也遇到了同样的问题

**Comment by jevonszmx** [comment]
> 请问你的问题解决了吗，我也遇到了同样的问题

如果你修改了cnew_loader.py 脚本里的 categories 变量，那么一定要保持cnn_model.py 脚本里的 num_classes 参数一致

**Comment by shulizangyujing** [comment]
谢谢啦～



---Original---
