### ISSUE TITLE
关于训练结果问题

### ISSUE THREAD

**Issue by Linxxx** [gaussic/text-classification-cnn-rnn#71]
你好 在你模型的基础上  我加入了我自己的数据  修改了可配置参数  扩展了三层双卷积核的卷积层  训练集最终收敛近乎百分之百 loss也极低  但是验证集准确度只有百分之50左右  predict的结果也有所偏差  屡次调试无果 不知道你有没有更好的调试方向

**Comment by Linxxx** [comment]
已解决

**Comment by ivyvideo** [comment]
你好，想问下如何解决的？
