### ISSUE TITLE
新人请教w和b的设置

### ISSUE THREAD

**Issue by VerusHao** [gaussic/text-classification-cnn-rnn#73]
您好，刚学习卷积神经网络，看了您的代码，没看明白权重和偏置在哪设置的

**Comment by gaussic** [comment]
tf.layers.conv1d 之类的层是已经高度封装好了的网络层，类似于接口，其中的权重和偏置是在接口内部随机初始化的。

详见：https://www.tensorflow.org/api_docs/python/tf/layers/conv1d
