### ISSUE TITLE
训练过程中提前结束

### ISSUE THREAD

**Issue by Chen65010445** [gaussic/text-classification-cnn-rnn#80]
训练到Epoch5 Iter到3800的时候，提示出现No optimization for a long time, auto-stopping...，然后就自动停止训练返回初始状态了 请问这种情况怎么解决？为什么会出现这种情况？

**Comment by gaussic** [comment]
建议不要down下来就直接run,要先看代码.

**Comment by Chen65010445** [comment]
不好意思没能仔细看代码 所以如果我想强制让训练过程达到比如说10000轮次的话还是需要对代码做调整，比如说删除会提前终止的语句之类的对不对？因为本人并不是学计算机及相关专业的所以可能问题比较低级，不好意思，还望您不吝赐教
