### ISSUE TITLE
词向量问题请教

### ISSUE THREAD

**Issue by VerusHao** [gaussic/text-classification-cnn-rnn#81]
你好，打断点调试发现词向量好像是one-hot的词向量，不是连续的实数的词向量，请问大神您的词向量是怎么设置的？

**Comment by gaussic** [comment]
词向量并不是 one-hot，只有标签是 one_hot。

**Comment by VerusHao** [comment]
但我打断点看feed_dict里的输入x都是0,1这两个数构成的tensor，而且训练好的词向量保存在哪里呢？

**Comment by gaussic** [comment]
<img width="1002" alt="training" src="https://user-images.githubusercontent.com/12946979/43715937-ca61cdc8-99b4-11e8-853a-6d03948e4f80.png">

**Comment by VerusHao** [comment]
对啊，这不是连续的实数向量，里面的数字对应的是它在字典中的id，剩余的补零

**Comment by gaussic** [comment]
你首先要搞清楚 one-hot 是什么,再去弄清楚 Embedding 的原理.

**Comment by shang271828** [comment]
感谢分享代码。

我的理解，这里是从字符层面进行文本分类，不是基于词这种语义单元的，所以没有采用word2vec之类的词嵌入

**Comment by Ludong418** [comment]
@VerusHao 就像作者说的， 你还没搞清one-hot和Embedding。先收集到一个全文的词-序号字典，然后每一句分词或分字后去字典找对应下标，这就是为啥你看到是整数的了，而Embedding，做着是用了get_variable默认初始化器初始化一个字embedding，你到embed_lookup那层去看看就知道了。
