### ISSUE TITLE
关于数据读入的小问题求教......

### ISSUE THREAD

**Issue by goryghost** [gaussic/text-classification-cnn-rnn#82]
是在Docker环境下运行的，尝试python run_cnn.py train 之后，每次在加载训练集的时候就会卡住然后显示killed......这个应该修改哪个参数来使其正常工作呢？
![image](https://user-images.githubusercontent.com/8553830/44084404-2c54e8b4-9fe9-11e8-8606-b87eff801cb2.png)
如图，本人小白，望不吝赐教

**Comment by gaussic** [comment]
没有遇到过这个问题，也许是超出内存了，可以尝试优化一下数据读取。
