### ISSUE TITLE
执行run_cnn.py时报如下错误

### ISSUE THREAD

**Issue by luoxianjiao** [gaussic/text-classification-cnn-rnn#83]
File "D:/stuff/NLP/text-classification-cnn-rnn-master/run_cnn.py", line 186, in <module>
    raise ValueError("""usage: python run_cnn.py [train / test]""")
ValueError: usage: python run_cnn.py [train / test]

**Comment by cy576013581** [comment]
后面没加train或者test吧
if len(sys.argv) != 2 or sys.argv[1] not in ['train', 'test']:
        raise ValueError("""usage: python run_rnn.py [train / test]""")
必须是python run_cnn.py train 或者是python run_cnn.py test 来表明是测试还是训练
