### ISSUE TITLE
请问设置embedding_dim（词向量维度）的意义是什么呢？

### ISSUE THREAD

**Issue by Ironeie** [gaussic/text-classification-cnn-rnn#84]
我读了代码，词汇表是每个汉字对应一个数字的简单映射，那为什么还要设置默认为64的词向量维度呢，以及在embedding层这样做呢？这里始终无法理解，望指点，谢谢

**Comment by PanJinquan** [comment]
我也是卡在这里：
```
       # 词向量映射
        with tf.device('/cpu:0'):
            embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim])
            embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)
```
这里创建embedding,那这个embedding的词嵌入到底是啥？望解答

**Comment by gaussic** [comment]
https://www.tensorflow.org/programmers_guide/embedding?hl=zh-cn

**Comment by Ironeie** [comment]
> https://www.tensorflow.org/programmers_guide/embedding?hl=zh-cn

谢谢解答，所以可以理解成词嵌入层的映射方法也是通过神经网络训练得出来的吗

**Comment by gaussic** [comment]
可以训练，也可以用其他方法预训练再载入，例如 word2vec、glove

**Comment by seven-linglx** [comment]
> 可以训练，也可以用其他方法预训练再载入，例如 word2vec、glove

在你的代码里，embedding是没有训练的，也没有用预训练载入，那它的值会全是0么？

**Comment by bleachyin** [comment]
在代码里我看值训练了train的vec而没有test，val的，这样在预测时候会有问题吧

**Comment by MambaMelon** [comment]
> 
> 
> 在代码里我看值训练了train的vec而没有test，val的，这样在预测时候会有问题吧

要是训练了test和val的，那还要它们预测和验证，就没效果了

**Comment by MambaMelon** [comment]
请问下，您这边是使用的是训练词向量的方式，但是训练数据不是很大，是否采用开源的词向量训练效果会更好呢？
