### ISSUE TITLE
关于中文数据的分词问题

### ISSUE THREAD

**Issue by xikunlun001** [gaussic/text-classification-cnn-rnn#85]
我下载了您提供的中文数据源，发现里面的文本是没有进行分词的。
请问您的code中是有分词的步骤还是并不需要分词？您训练的word embedding 是词向量还是character级别的词向量
我如果有自己的数据是否是label   后面接分好词的文本内容呢？
感谢~~~

**Comment by YUTianGong** [comment]
不需要，这个是字符级别的，相当于字向量，并不是词向量
