### ISSUE TITLE
关于predict.py的问题

### ISSUE THREAD

**Issue by YUTianGong** [gaussic/text-classification-cnn-rnn#86]
lz的代码思路清晰，收敛速度快，但是有一个问题就是用rnn_cnn.py对测试数据计算的p，r，f和用predict.py计算的结果不一样，predict.py的结果很差，这是为什么啊？？代码基本上没有变动

**Comment by gaussic** [comment]
```python
def read_test_data(filename):
    contents, labels = [], []
    with open(filename, 'r', encoding='utf-8') as f:
        for line in f:
            label, content = line.strip().split('\t')
            contents.append(content)
            labels.append(label)
    return contents, labels

if __name__ == '__main__':
    cnn_model = CnnModel()
    # test_demo = ['三星ST550以全新的拍摄方式超越了以往任何一款数码相机',
    #              '热火vs骑士前瞻：皇帝回乡二番战 东部次席唾手可得新浪体育讯北京时间3月30日7:00']
    contents, labels = read_test_data("data/cnews/cnews.test.txt")
    cat_to_id = cnn_model.cat_to_id
    labels_id = [cat_to_id[x] for x in labels]
    targets_id = []
    cnt = 0
    for i in range(len(contents)):
        label = cnn_model.predict(contents[i])
        if label == labels[i]:
            cnt += 1
        targets_id.append(cat_to_id[label])
    print(cnt / len(contents))
    # 评估
    print("Precision, Recall and F1-Score...")
    print(metrics.classification_report(labels_id, targets_id, target_names=cnn_model.categories))
```

以下是实测结果：

```
0.9615
Precision, Recall and F1-Score...
             precision    recall  f1-score   support

         体育       0.99      1.00      0.99      1000
         财经       0.96      0.99      0.97      1000
         房产       0.99      1.00      0.99      1000
         家居       0.99      0.86      0.92      1000
         教育       0.89      0.95      0.92      1000
         科技       0.94      0.98      0.96      1000
         时尚       0.96      0.97      0.97      1000
         时政       0.96      0.93      0.94      1000
         游戏       0.98      0.97      0.98      1000
         娱乐       0.98      0.97      0.97      1000

avg / total       0.96      0.96      0.96     10000
```

**Comment by YUTianGong** [comment]
好的，谢谢，我将原始的rnn_cnn.py的test()函数进行修改，来完成预测任务，确实也能得到很好的效果，代码很清晰，简洁，感觉字符级别的向量在文本分类任务上是不是比词向量要好，为我们进行文本分类提供了一个很好的思路。然后，我进行测试的数据集是2分类的，文本相对较短，目前prf都不到90%，不知道在这个项目里作者有没有什么优化的建议呢？

________________________________

Yutian Gong

Postgraduate
Zhongnan University of Economica and Law

________________________________
发件人: gaussic <notifications@github.com>
发送时间: 2018年9月1日 0:16
收件人: gaussic/text-classification-cnn-rnn
抄送: YUTianGong; Author
主题: Re: [gaussic/text-classification-cnn-rnn] 关于predict.py的问题 (#86)


def read_test_data(filename):
    contents, labels = [], []
    with open(filename, 'r', encoding='utf-8') as f:
        for line in f:
            label, content = line.strip().split('\t')
            contents.append(content)
            labels.append(label)
    return contents, labels

if __name__ == '__main__':
    cnn_model = CnnModel()
    # test_demo = ['三星ST550以全新的拍摄方式超越了以往任何一款数码相机',
    #              '热火vs骑士前瞻：皇帝回乡二番战 东部次席唾手可得新浪体育讯北京时间3月30日7:00']
    contents, labels = read_test_data("data/cnews/cnews.test.txt")
    cat_to_id = cnn_model.cat_to_id
    labels_id = [cat_to_id[x] for x in labels]
    targets_id = []
    cnt = 0
    for i in range(len(contents)):
        label = cnn_model.predict(contents[i])
        if label == labels[i]:
            cnt += 1
        targets_id.append(cat_to_id[label])
    print(cnt / len(contents))
    # 评估
    print("Precision, Recall and F1-Score...")
    print(metrics.classification_report(labels_id, targets_id, target_names=cnn_model.categories))

以下是实测结果：

0.9615
Precision, Recall and F1-Score...
             precision    recall  f1-score   support

         体育       0.99      1.00      0.99      1000
         财经       0.96      0.99      0.97      1000
         房产       0.99      1.00      0.99      1000
         家居       0.99      0.86      0.92      1000
         教育       0.89      0.95      0.92      1000
         科技       0.94      0.98      0.96      1000
         时尚       0.96      0.97      0.97      1000
         时政       0.96      0.93      0.94      1000
         游戏       0.98      0.97      0.98      1000
         娱乐       0.98      0.97      0.97      1000

avg / total       0.96      0.96      0.96     10000


―

**Comment by gaussic** [comment]
这个就要看如何调参了，数据集的质量也是很重要的，你可以适当地修改模型的参数，或者增加几个网络层，然后测试一下效果。

**Comment by YUTianGong** [comment]
好的好的，谢谢你的耐心解答哦！！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Chen65010445** [comment]
请问您使用predict.py的时候有没有出现过一段话出现很多同样的分类项，因为我出现了下面的情况：
<pre>2018-09-05 09:44:36.593198: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-09-05 09:44:36.652532: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-05 09:44:36.653205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.60GiB
2018-09-05 09:44:36.653224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-09-05 09:44:37.161408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-05 09:44:37.161446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-09-05 09:44:37.161453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-09-05 09:44:37.161672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3333 MB memory) -&gt; physical GPU (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
家居
家居
家居
家居
家居
家居
家居
家居
家居
家居
家居
家居
家居
家居
家居
家居
家居
家居
</pre>

**Comment by YUTianGong** [comment]
@Chen65010445 我也确实碰到过这个问题，所以我把run_cnn.py的test( )模块修改了拿来做预测，修改完之后的效果很正常。

**Comment by Chen65010445** [comment]
那请问您是怎么修改的代码呢？能不能给个参考？

**Comment by Chen65010445** [comment]
@YUTianGong 那请问您是怎么修改代码的呢 能不能展示一下给个参考？

**Comment by YUTianGong** [comment]
@Chen65010445 run_cnn里面的y_pred_cls就是预测结果。

**Comment by Chen65010445** [comment]
@YUTianGong 那你具体是怎么修改的呢？

**Comment by kikizxd** [comment]
请问预测都是同一类这个问题解决了么？我改用test，将batch_size = 1还是不行，求帮助
