### ISSUE TITLE
predict分类结果怎么出现概率

### ISSUE THREAD

**Issue by cy576013581** [gaussic/text-classification-cnn-rnn#87]
目前的predict的分类只有一个分类的结果，能否带出这个分类的概率呢

**Comment by gaussic** [comment]
修改 cnn_model 或 rnn_model 中分类器部分，将输出分来改为输出分类概率。

**Comment by cy576013581** [comment]
@gaussic 想要的结果是哪个分类，属于该分类的概率，类似于Fasttext那种输出

**Comment by gaussic** [comment]
修改 cnn_model 或 rnn_model 中分类器部分，将输出分类改为输出分类概率。

**Comment by rzechen** [comment]
你好，请问你有实现输出概率结果吗？方便共享一下代码吗
