### ISSUE TITLE
大神，你模型中embedding的词向量和word2vec的词向量有区别吗

### ISSUE THREAD

**Issue by hongBry** [gaussic/text-classification-cnn-rnn#9]
你模拟直接用
embedding = tf.get_variable('embedding', [self.config.vocab_size, self.config.embedding_dim])
embedding_inputs = tf.nn.embedding_lookup(embedding, self.input_x)
和gensim的word2vec有区别吗

**Comment by gaussic** [comment]
模型中的Embedding层和word2vec有很大的区别，但是都是殊途同归的。你大可以把这个Embedding层看作是一个全连接层y=Wx+b，W就是词向量的矩阵。初始是，W是随机初始化的，然后在训练的过程中会逐步的调整这个词向量矩阵。因此，理论上，模型中的Embedding会更加契合当前的任务。而word2vec的话，则更加适用于通用的任务了。

**Comment by hongBry** [comment]
soga，也就是说你模型在训练cnn或rnn参数的同时也训练词向量矩阵参数，还有，大神，我看你代码中生成的词id的时候，你会过滤掉一些低频词，这样做有好处吗

**Comment by gaussic** [comment]
这个就要看具体的场景了。一般来说，如果使用的是词语级别的模型的话，一个数据集分词后大约有数十万个单词，而大部分的单词基本上出现不超过5词，这些词在一定程度上是没有什么意义的。此外，除了这些低频词，还有一些高频词，比如，你、我、他、是、这是之类的，也可以去掉，有时候能带来一些性能的增益。

如果觉得对你有帮助，欢迎star，^_^

**Comment by hongBry** [comment]
大神，我看你代码：
    embedding_dim = 64      # 词向量维度
    

    num_layers= 2           # 隐藏层层数
    hidden_dim = 128        # 隐藏层神经元

其中embedding层输出应该是【batch，64】
那hidden_dim不应该是64吗？

**Comment by gaussic** [comment]
这个问题的话，你就要取查一查关于神经网络的定义了，需要了解一些神经网络参数的基础知识，或许对你有帮助。

看看这篇：[神经网络](http://ufldl.stanford.edu/wiki/index.php/%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C)
