### ISSUE TITLE
run_rnn.py时抛出异常

### ISSUE THREAD

**Issue by Ijustakid** [gaussic/text-classification-cnn-rnn#92]
if __name__ == '__main__':
    if len(sys.argv) != 2 or sys.argv[1] not in ['train', 'test']:
        raise ValueError("""usage: python run_rnn.py [train / test]""")

ValueError: usage: python run_rnn.py [train / test]
请问如何解决？

**Comment by Ijustakid** [comment]
__

**Comment by cherish-dan** [comment]
你好，这个问题解决了吗？我也遇到了这个问题，不知道该怎么解决

**Comment by Ijustakid** [comment]
@cherish-dan 当时解决了，但是过太久了，已经忘了......
