### ISSUE TITLE
您好，我在训练数据时发生GPU资源耗尽的错误

### ISSUE THREAD

**Issue by Ijustakid** [gaussic/text-classification-cnn-rnn#96]
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Ran out of GPU memory when allocating 0 bytes for 
[[Node: optimize/SoftmaxCrossEntropyWithLogits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](optimize/Reshape, optimize/Reshape_1)]]

[[Node: optimize/Mean/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_251_optimize/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by gaussic** [comment]
机器性能不佳，建议更换

**Comment by Ijustakid** [comment]
> 机器性能不佳，建议更换

Titan XP......

**Comment by gaussic** [comment]
多试几次

**Comment by Ijustakid** [comment]
> 多试几次

好的，感谢指点
